board_addr = "https://www.luogu.com.cn/paintboard"
websocket_addr = "wss://ws.luogu.com.cn/ws"
cookie_dir = "cookie_dir"
node_file = "node.json"
wait_time = 30
thread_num = 5
board_width = 1000
board_height = 600
